### ISSUE TITLE
.woff2 fonts in npm package

### ISSUE THREAD

**Issue by davidbarredo** [earaujoassis/ubuntu-fontface#14]
I've installed the latest ubuntu-fontface version package from npm (v.0.1.11) and there aren't any woff2 files.

However, in this project the version 0.1.13 added the woff2 files, so, could you please update the npm package with the latest github release?

Thanks!

**Comment by earaujoassis** [comment]
Hi, @davidbarredo. I've tried do publish the npm package again, but it seems that's not the right solution to go. I'll check later today what I need to do in order to force an update in npm. Once I fix that, I'll let you know. Please let me know if a forced/pinned version in `package.json` file doesn't fix that. Thank you!

**Comment by davidbarredo** [comment]
I've tried with the pinned version (0.1.13) but nothing is installed. 

The error displayed:
`npm ERR! No compatible version found: ubuntu-fontface@0.1.13`
`npm ERR! Valid install targets:`
`npm ERR! 0.1.11, 0.1.10`

**Comment by earaujoassis** [comment]
@davidbarredo Problem solved! Thanks :)
