### ISSUE TITLE
cyrillic symbols aren't presented

### ISSUE THREAD

**Issue by redscotina** [earaujoassis/ubuntu-fontface#4]
subj

**Comment by earaujoassis** [comment]
@redscotina I'll take a look soon.

**Comment by earaujoassis** [comment]
@rkrzewski Hey Rafał, I've seen your forked this project; does your fork solve this problem with Cyrillic characters? I've also seen you added some niceties to the project. Would you mind to share that? Many thanks in advance!

**Comment by rkrzewski** [comment]
@earaujoassis unfortunately, no. We've added only Central European latin characters to the font, because that was our particular need. I can lodge a PR with that change if you wish.

The other changes were needed only because we needed to package the changed font as a [webjar](http://www.webjars.org/) for a JavaEE application, so they are not useful for the general public.
